name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -name: Check out the code
